export const DOG_BREEDS = [
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'French Bulldog',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'German Shorthaired Pointer',
  'Yorkshire Terrier',
  'Siberian Husky',
  'Dachshund',
  'Pembroke Welsh Corgi',
  'Australian Shepherd',
  'Boston Terrier',
  'Border Collie',
  'Boxer',
  'Cocker Spaniel',
  'Great Dane',
  'Chihuahua',
  'Shih Tzu',
  'Pomeranian',
  'Jack Russell Terrier',
  'Maltese',
  'Bernese Mountain Dog',
  'Mastiff',
  'Bichon Frise',
  'Bloodhound',
  'Basenji',
  'Akita',
  'Afghan Hound',
  'Airedale Terrier',
  'American Pit Bull Terrier',
  'Basset Hound',
  'Bull Terrier',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chow Chow',
  'Collie',
  'Dalmatian',
  'Doberman Pinscher',
  'English Setter',
  'Fox Terrier',
  'Great Pyrenees',
  'Greyhound',
  'Irish Setter',
  'Italian Greyhound',
  'Newfoundland',
  'Norwegian Elkhound',
  'Old English Sheepdog',
  'Papillon',
  'Pekingese',
  'Pointer',
  'Pug',
  'Saint Bernard',
  'Samoyed',
  'Scottish Terrier',
  'Shetland Sheepdog',
  'Springer Spaniel',
  'Standard Schnauzer',
  'Vizsla',
  'Weimaraner',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Mixed Breed'
] as const

export const CAT_BREEDS = [
  'Domestic Shorthair',
  'Domestic Longhair',
  'Persian',
  'Maine Coon',
  'Ragdoll',
  'British Shorthair',
  'Siamese',
  'Abyssinian',
  'Russian Blue',
  'American Shorthair',
  'Scottish Fold',
  'Sphynx',
  'Bengal',
  'Birman',
  'Oriental',
  'Devon Rex',
  'Cornish Rex',
  'Manx',
  'Norwegian Forest Cat',
  'Siberian',
  'Turkish Angora',
  'Exotic Shorthair',
  'Burmese',
  'Tonkinese',
  'Balinese',
  'Egyptian Mau',
  'Himalayan',
  'Japanese Bobtail',
  'Korat',
  'LaPerm',
  'Ocicat',
  'Ragamuffin',
  'Selkirk Rex',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Turkish Van',
  'American Curl',
  'Bombay',
  'Chartreux',
  'Havana Brown',
  'Munchkin',
  'Nebelung',
  'Pixie-bob',
  'Savannah',
  'Mixed Breed'
] as const

export type DogBreed = typeof DOG_BREEDS[number]
export type CatBreed = typeof CAT_BREEDS[number]

export function getBreeds(species: 'dog' | 'cat'): readonly string[] {
  return species === 'dog' ? DOG_BREEDS : CAT_BREEDS
}

export const IDEAL_SLEEP_HOURS = {
  dog: { min: 12, max: 14 },
  cat: { min: 12, max: 16 }
} as const